name: complex_flutter_app
description: A complex Flutter application with many dependencies
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  dio: ^5.3.2
  shared_preferences: ^2.0.15
  provider: ^6.0.3
  cached_network_image: ^3.2.3
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  url_launcher: ^6.1.14
  webview_flutter: ^4.4.1
  json_annotation: ^4.8.1
  intl: ^0.18.1
  crypto: ^3.0.3
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  mockito: ^5.4.2

flutter:
  uses-material-design: true

