name: conflicted_flutter_app
description: A Flutter application with dependency conflicts for testing resolution
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Intentional conflicts for testing
  http: ^0.13.5
  dio: ^4.0.0  # Older version that might conflict with http
  shared_preferences: ^2.0.15
  provider: ^5.0.0  # Older version
  cached_network_image: ^3.2.3
  # This creates a potential conflict
  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # Conflicting version in dev dependencies
  http: ^0.12.0  # Different version than in dependencies
  meta: ^1.9.0   # Different version than in dependencies

flutter:
  uses-material-design: true

